export const GET_INCIDENTS = "GET_INCIDENTS";
export const DELETE_INCIDENT = "DELETE_INCIDENT";
export const ADD_INCIDENT = "ADD_INCIDENT";
export const UPDATE_INCIDENT = "UPDATE_INCIDENT";
export const GET_SINGLE_INCIDENT = "GET_SINGLE_INCIDENT";